### ISSUE TITLE
Add option to log data and groups on ComponentLoader

### ISSUE THREAD

**Issue by automata** [noflo/noflo-nodejs#43]
As suggested by @jonnor I'm using something like [this](https://gist.github.com/automata/332ddf6b83b66c5900f9#file-component-coffee-L21-L25) to enable logging data/groups.

It would be interesting to add this option to every component, maybe on ComponentLoader?

In some way related with #15.

**Comment by jonnor** [comment]
How is `--debug` not what you want?

**Comment by jonnor** [comment]
Closing, above option traces the whole network, including all subcomponents, with basically exactly same formatting.

**Comment by automata** [comment]
An use case is when running a Chai test: it's not possible to use `--debug` because we use `ComponentLoader` directly to load the component we want on test.

Another option is to add [this](https://gist.github.com/automata/332ddf6b83b66c5900f9) on `grunt-init-noflo` so someone can `DEBUG_NOFLO=true grunt`. But only new component libraries using `grunt-init-noflo` as bootstrap would benefit with that.

**Comment by jonnor** [comment]
When you are doing Chai tests with NoFlo.ComponentLoader you are not using
noflo-nodejs at all (only NoFlo).
So either the feature would go into NoFlo itself. Can create issue there if
we don't have any yet.

Or you'd use something like fbp-spec where you do use noflo-nodejs.
In general I think Flowtrace instead of logging to stdout is the way to go
though ;)
