### ISSUE TITLE
Console logs not outputting

### ISSUE THREAD

**Issue by aretecode** [noflo/noflo-nodejs#75]
Console logs are not output to cli when using fbp-spec

**Comment by jonnor** [comment]
`fbp-spec` connects over the FBP protocol, so this likely means that the `network:output` messages are not being sent.

**Comment by bergie** [comment]
By default they're shown in the console where noflo-nodejs runs. But when you start it on background (like often with fbp-spec), you need to provide the `--capture-output=true` flag when starting noflo-nodejs. This way they'll be send to the client instead of emitted locally.

Example: https://github.com/noflo/noflo-markdown/blob/master/spec/fbpspec.coffee
